### ISSUE TITLE
'Error Parsing failed' error

### ISSUE THREAD

**Issue by RSchwoerer** [trailofbits/vscode-sarif-explorer#21]
I am unable to open any sarif output files and see the below error. Maybe related to #11.
These files are generated by MSBuild for a .NET project.

`Failed to load "c:\Users\schwoer\Downloads\compiler-diagnostics.sarif": Error: Parsing failed: TypeError: Cannot read properties of undefined (reading 'artifactLocation').`

Sanitized and simplified example to repro the issue:
[compiler-diagnostics.sarif.json](https://github.com/trailofbits/vscode-sarif-explorer/files/15179192/compiler-diagnostics.sarif.json)

**Comment by Vasco-jofra** [comment]
Thanks you for the report and for including a reproducible! I'll look at it soon!

**Comment by Vasco-jofra** [comment]
This SARIF uses this sort of thing as a location:
```yml
          "locations": [
            {
              "resultFile": {
                "uri": "file:///C:/Users/bob/source/repos/foo/Source/Common/Utils/Bar.cs",
                "region": {
                  "startLine": 34,
                  "startColumn": 1,
                  "endLine": 34,
                  "endColumn": 1
                }
              }
            }
          ]
```

This is not valid SARIF v2.1.0, as you can see in the spec: https://docs.oasis-open.org/sarif/sarif/v2.1.0/csprd01/sarif-v2.1.0-csprd01.html#_Toc10541108.

It seems to use an old SARIF version, which we do not support and are unlikely to support in the future.
